"""baseline skema lengkap

Revision ID: 49123ed7cc98
Revises:
Create Date: 2026-08-24 08:38:11.823486

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "49123ed7cc98"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=60), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("education", sa.String(length=255), nullable=True),
        sa.Column("experience_years", sa.Integer(), nullable=True),
        sa.Column("current_company", sa.String(length=255), nullable=True),
        sa.Column("expected_salary", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("skills", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=120), nullable=True),
        sa.Column("cv_object_key", sa.String(length=500), nullable=True),
        sa.Column("cv_file_name", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "screening",
                "interview",
                "offered",
                "placed",
                "rejected",
                "archived",
                name="candidatestatus",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_candidates_full_name"), "candidates", ["full_name"], unique=False)
    op.create_index(op.f("ix_candidates_status"), "candidates", ["status"], unique=False)
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_journal_entries_entry_date"), "journal_entries", ["entry_date"], unique=False
    )
    op.create_table(
        "payroll_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "final", name="payrollrunstatus", native_enum=False, length=50),
            nullable=False,
        ),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payroll_runs_month"), "payroll_runs", ["month"], unique=False)
    op.create_index(op.f("ix_payroll_runs_status"), "payroll_runs", ["status"], unique=False)
    op.create_index(op.f("ix_payroll_runs_year"), "payroll_runs", ["year"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "admin",
                "business_dev",
                "recruiter",
                "hr",
                "operations",
                "finance",
                "management",
                name="userrole",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "journal_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("account_code", sa.String(length=20), nullable=False),
        sa.Column("debit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("credit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["journal_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_journal_lines_account_code"), "journal_lines", ["account_code"], unique=False
    )
    op.create_index(op.f("ix_journal_lines_entry_id"), "journal_lines", ["entry_id"], unique=False)
    op.create_table(
        "leads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("contact_name", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=60), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("estimated_headcount", sa.Integer(), nullable=True),
        sa.Column("estimated_value", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column(
            "stage",
            sa.Enum(
                "lead",
                "contact",
                "presentation",
                "quotation",
                "negotiation",
                "won",
                "lost",
                name="leadstage",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leads_company_name"), "leads", ["company_name"], unique=False)
    op.create_index(op.f("ix_leads_stage"), "leads", ["stage"], unique=False)
    op.create_table(
        "clients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("npwp", sa.String(length=50), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("pic_name", sa.String(length=255), nullable=True),
        sa.Column("pic_phone", sa.String(length=60), nullable=True),
        sa.Column("pic_email", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "churned", name="clientstatus", native_enum=False, length=50),
            nullable=False,
        ),
        sa.Column("contract_start", sa.Date(), nullable=True),
        sa.Column("contract_end", sa.Date(), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_contract_end"), "clients", ["contract_end"], unique=False)
    op.create_index(op.f("ix_clients_name"), "clients", ["name"], unique=False)
    op.create_table(
        "lead_activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column(
            "activity_type",
            sa.Enum(
                "call",
                "meeting",
                "email",
                "note",
                name="activitytype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lead_activities_lead_id"), "lead_activities", ["lead_id"], unique=False
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_no", sa.String(length=50), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("payroll_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("fee_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("ppn_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("ppn_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("pph23_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("pph23_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_due", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "sent",
                "paid",
                "cancelled",
                name="invoicestatus",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("issued_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", "year", "month", name="uq_invoice_period"),
    )
    op.create_index(op.f("ix_invoices_client_id"), "invoices", ["client_id"], unique=False)
    op.create_index(op.f("ix_invoices_due_date"), "invoices", ["due_date"], unique=False)
    op.create_index(op.f("ix_invoices_invoice_no"), "invoices", ["invoice_no"], unique=True)
    op.create_index(op.f("ix_invoices_month"), "invoices", ["month"], unique=False)
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_index(op.f("ix_invoices_year"), "invoices", ["year"], unique=False)
    op.create_table(
        "job_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("headcount", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("salary_min", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "screening",
                "interview",
                "offering",
                "filled",
                "closed",
                name="joborderstatus",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_orders_client_id"), "job_orders", ["client_id"], unique=False)
    op.create_index(op.f("ix_job_orders_status"), "job_orders", ["status"], unique=False)
    op.create_table(
        "legal_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "pks",
                "addendum",
                "npwp",
                "nib",
                "other",
                name="documenttype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_legal_documents_client_id"), "legal_documents", ["client_id"], unique=False
    )
    op.create_table(
        "ai_screenings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("job_order_id", sa.Uuid(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "recommended",
                "consider",
                "reject",
                name="screeningverdict",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("strengths_json", sa.Text(), nullable=False),
        sa.Column("risks_json", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_order_id"],
            ["job_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_screenings_candidate_id"), "ai_screenings", ["candidate_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_screenings_job_order_id"), "ai_screenings", ["job_order_id"], unique=False
    )
    op.create_table(
        "cash_flow_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("inflow", "outflow", name="cashflowdirection", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("invoice_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cash_flow_entries_category"), "cash_flow_entries", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_cash_flow_entries_direction"), "cash_flow_entries", ["direction"], unique=False
    )
    op.create_index(
        op.f("ix_cash_flow_entries_entry_date"), "cash_flow_entries", ["entry_date"], unique=False
    )
    op.create_table(
        "placements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("job_order_id", sa.Uuid(), nullable=False),
        sa.Column("offered_salary", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "accepted",
                "onboarded",
                "cancelled",
                name="placementstatus",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_order_id"],
            ["job_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id", "job_order_id", name="uq_candidate_jo"),
    )
    op.create_index(
        op.f("ix_placements_candidate_id"), "placements", ["candidate_id"], unique=False
    )
    op.create_index(
        op.f("ix_placements_job_order_id"), "placements", ["job_order_id"], unique=False
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("placement_id", sa.Uuid(), nullable=True),
        sa.Column("employee_no", sa.String(length=50), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("ktp_no", sa.String(length=50), nullable=True),
        sa.Column("npwp_no", sa.String(length=50), nullable=True),
        sa.Column("bpjs_kesehatan_no", sa.String(length=50), nullable=True),
        sa.Column("bpjs_ketenagakerjaan_no", sa.String(length=50), nullable=True),
        sa.Column("phone", sa.String(length=60), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("bank_name", sa.String(length=100), nullable=True),
        sa.Column("bank_account", sa.String(length=100), nullable=True),
        sa.Column("join_date", sa.Date(), nullable=True),
        sa.Column(
            "marital_status",
            sa.Enum("single", "married", name="maritalstatus", native_enum=False, length=50),
            nullable=True,
        ),
        sa.Column("dependents", sa.Integer(), nullable=False),
        sa.Column("base_salary", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "resigned", name="employeestatus", native_enum=False, length=50),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["placement_id"],
            ["placements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employees_employee_no"), "employees", ["employee_no"], unique=True)
    op.create_index(op.f("ix_employees_full_name"), "employees", ["full_name"], unique=False)
    op.create_index(op.f("ix_employees_placement_id"), "employees", ["placement_id"], unique=False)
    op.create_index(op.f("ix_employees_status"), "employees", ["status"], unique=False)
    op.create_table(
        "ai_document_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding_json", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "chunk_index", name="uq_chunk_source_idx"),
    )
    op.create_index(
        op.f("ix_ai_document_chunks_source_id"), "ai_document_chunks", ["source_id"], unique=False
    )
    op.create_table(
        "attendance_summaries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("present_days", sa.Integer(), nullable=False),
        sa.Column("overtime_hours", sa.Integer(), nullable=False),
        sa.Column("client_approved", sa.Boolean(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "year", "month", name="uq_attendance_period"),
    )
    op.create_index(
        op.f("ix_attendance_summaries_client_approved"),
        "attendance_summaries",
        ["client_approved"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_summaries_employee_id"),
        "attendance_summaries",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_summaries_month"), "attendance_summaries", ["month"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_summaries_year"), "attendance_summaries", ["year"], unique=False
    )
    op.create_table(
        "employee_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "ktp",
                "npwp",
                "bpjs_kesehatan",
                "bpjs_ketenagakerjaan",
                "other",
                name="hrdocumenttype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employee_documents_employee_id"),
        "employee_documents",
        ["employee_id"],
        unique=False,
    )
    op.create_table(
        "employment_contracts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("contract_no", sa.String(length=100), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "sign_status",
            sa.Enum("waiting", "signed", name="contractsignstatus", native_enum=False, length=50),
            nullable=False,
        ),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("object_key", sa.String(length=500), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("mime_type", sa.String(length=120), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employment_contracts_contract_no"),
        "employment_contracts",
        ["contract_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employment_contracts_employee_id"),
        "employment_contracts",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employment_contracts_end_date"), "employment_contracts", ["end_date"], unique=False
    )
    op.create_index(
        op.f("ix_employment_contracts_sign_status"),
        "employment_contracts",
        ["sign_status"],
        unique=False,
    )
    op.create_table(
        "payslips",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("base_salary", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("allowance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("overtime_hours", sa.Integer(), nullable=False),
        sa.Column("overtime_rate", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("overtime_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("deductions", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("gross", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("pph21_method", sa.String(length=20), nullable=False),
        sa.Column("tax_pph21", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("net_pay", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["payroll_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "employee_id", name="uq_run_employee"),
    )
    op.create_index(op.f("ix_payslips_employee_id"), "payslips", ["employee_id"], unique=False)
    op.create_index(op.f("ix_payslips_run_id"), "payslips", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payslips_run_id"), table_name="payslips")
    op.drop_index(op.f("ix_payslips_employee_id"), table_name="payslips")
    op.drop_table("payslips")
    op.drop_index(op.f("ix_employment_contracts_sign_status"), table_name="employment_contracts")
    op.drop_index(op.f("ix_employment_contracts_end_date"), table_name="employment_contracts")
    op.drop_index(op.f("ix_employment_contracts_employee_id"), table_name="employment_contracts")
    op.drop_index(op.f("ix_employment_contracts_contract_no"), table_name="employment_contracts")
    op.drop_table("employment_contracts")
    op.drop_index(op.f("ix_employee_documents_employee_id"), table_name="employee_documents")
    op.drop_table("employee_documents")
    op.drop_index(op.f("ix_attendance_summaries_year"), table_name="attendance_summaries")
    op.drop_index(op.f("ix_attendance_summaries_month"), table_name="attendance_summaries")
    op.drop_index(op.f("ix_attendance_summaries_employee_id"), table_name="attendance_summaries")
    op.drop_index(
        op.f("ix_attendance_summaries_client_approved"), table_name="attendance_summaries"
    )
    op.drop_table("attendance_summaries")
    op.drop_index(op.f("ix_ai_document_chunks_source_id"), table_name="ai_document_chunks")
    op.drop_table("ai_document_chunks")
    op.drop_index(op.f("ix_employees_status"), table_name="employees")
    op.drop_index(op.f("ix_employees_placement_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_full_name"), table_name="employees")
    op.drop_index(op.f("ix_employees_employee_no"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_placements_job_order_id"), table_name="placements")
    op.drop_index(op.f("ix_placements_candidate_id"), table_name="placements")
    op.drop_table("placements")
    op.drop_index(op.f("ix_cash_flow_entries_entry_date"), table_name="cash_flow_entries")
    op.drop_index(op.f("ix_cash_flow_entries_direction"), table_name="cash_flow_entries")
    op.drop_index(op.f("ix_cash_flow_entries_category"), table_name="cash_flow_entries")
    op.drop_table("cash_flow_entries")
    op.drop_index(op.f("ix_ai_screenings_job_order_id"), table_name="ai_screenings")
    op.drop_index(op.f("ix_ai_screenings_candidate_id"), table_name="ai_screenings")
    op.drop_table("ai_screenings")
    op.drop_index(op.f("ix_legal_documents_client_id"), table_name="legal_documents")
    op.drop_table("legal_documents")
    op.drop_index(op.f("ix_job_orders_status"), table_name="job_orders")
    op.drop_index(op.f("ix_job_orders_client_id"), table_name="job_orders")
    op.drop_table("job_orders")
    op.drop_index(op.f("ix_invoices_year"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_month"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_invoice_no"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_due_date"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_client_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_lead_activities_lead_id"), table_name="lead_activities")
    op.drop_table("lead_activities")
    op.drop_index(op.f("ix_clients_name"), table_name="clients")
    op.drop_index(op.f("ix_clients_contract_end"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_leads_stage"), table_name="leads")
    op.drop_index(op.f("ix_leads_company_name"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_journal_lines_entry_id"), table_name="journal_lines")
    op.drop_index(op.f("ix_journal_lines_account_code"), table_name="journal_lines")
    op.drop_table("journal_lines")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_payroll_runs_year"), table_name="payroll_runs")
    op.drop_index(op.f("ix_payroll_runs_status"), table_name="payroll_runs")
    op.drop_index(op.f("ix_payroll_runs_month"), table_name="payroll_runs")
    op.drop_table("payroll_runs")
    op.drop_index(op.f("ix_journal_entries_entry_date"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_candidates_status"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_full_name"), table_name="candidates")
    op.drop_table("candidates")
    # ### end Alembic commands ###
