"""tabel esign_requests

Revision ID: b209f3b027c1
Revises: 49123ed7cc98
Create Date: 2026-08-24 08:50:23.855276

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b209f3b027c1"
down_revision: str | None = "49123ed7cc98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "esign_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_document_id", sa.String(length=255), nullable=False),
        sa.Column("signer_name", sa.String(length=255), nullable=False),
        sa.Column("signer_email", sa.String(length=255), nullable=False),
        sa.Column("sign_url", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "sent",
                "viewed",
                "completed",
                "declined",
                "expired",
                "failed",
                name="esignstatus",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("detail_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["employment_contracts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_esign_requests_contract_id"), "esign_requests", ["contract_id"], unique=False
    )
    op.create_index(
        op.f("ix_esign_requests_provider_document_id"),
        "esign_requests",
        ["provider_document_id"],
        unique=False,
    )
    op.create_index(op.f("ix_esign_requests_status"), "esign_requests", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_esign_requests_status"), table_name="esign_requests")
    op.drop_index(op.f("ix_esign_requests_provider_document_id"), table_name="esign_requests")
    op.drop_index(op.f("ix_esign_requests_contract_id"), table_name="esign_requests")
    op.drop_table("esign_requests")
    # ### end Alembic commands ###
