"""kolom jkk_risk_category karyawan

Revision ID: d1ce2c59c7da
Revises: b209f3b027c1
Create Date: 2026-08-24 09:18:58.583884

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d1ce2c59c7da"
down_revision: str | None = "b209f3b027c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employees", sa.Column("jkk_risk_category", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "jkk_risk_category")
    # ### end Alembic commands ###
